/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI.Student;

import UI.MainJFrame;
import UI.Student.StudentChosenCoursesJPanel;
import UI.Transcript.TranscriptJPanel;
import java.awt.CardLayout;
import java.time.LocalDate;
import java.util.Date;
import java.time.ZoneId;
import javax.swing.JOptionPane;
import model.Main.EducationSystem;
import Model.Student.Student;

/**
 *
 * @author riyasingh
 */
public class StudentDashboard extends javax.swing.JFrame {


    /**
     * Creates new form StudentDashboard
     */
    EducationSystem lc;
    Student sc;
    public StudentDashboard(EducationSystem lc) {
        initComponents();
        this.lc = lc;
        this.sc = sc;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        btnmyinfo = new javax.swing.JButton();
        txtstudentid = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnlogout = new javax.swing.JButton();
        btnmycourses = new javax.swing.JButton();
        btnDeclare = new javax.swing.JButton();
        btnaddcourse = new javax.swing.JButton();
        txtstudentname = new javax.swing.JTextField();
        studentcardpanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setForeground(new java.awt.Color(204, 204, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnmyinfo.setBackground(new java.awt.Color(0, 153, 153));
        btnmyinfo.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        btnmyinfo.setText("MY INFORMATION");
        btnmyinfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmyinfoActionPerformed(evt);
            }
        });
        jPanel1.add(btnmyinfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        txtstudentid.setEditable(false);
        txtstudentid.setBackground(new java.awt.Color(255, 255, 255));
        txtstudentid.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtstudentid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtstudentidActionPerformed(evt);
            }
        });
        jPanel1.add(txtstudentid, new org.netbeans.lib.awtextra.AbsoluteConstraints(794, 10, 40, 30));

        jLabel1.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText(":");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 20, 10, 24));

        btnlogout.setBackground(new java.awt.Color(0, 153, 153));
        btnlogout.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        btnlogout.setText("LOGOUT");
        btnlogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlogoutActionPerformed(evt);
            }
        });
        jPanel1.add(btnlogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        btnmycourses.setBackground(new java.awt.Color(0, 153, 153));
        btnmycourses.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        btnmycourses.setText("MY COURSES");
        btnmycourses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmycoursesActionPerformed(evt);
            }
        });
        jPanel1.add(btnmycourses, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 110, -1, -1));

        btnDeclare.setBackground(new java.awt.Color(0, 153, 153));
        btnDeclare.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        btnDeclare.setText("DECLARE");
        btnDeclare.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeclareActionPerformed(evt);
            }
        });
        jPanel1.add(btnDeclare, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 110, -1, -1));

        btnaddcourse.setBackground(new java.awt.Color(0, 153, 153));
        btnaddcourse.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        btnaddcourse.setText("ADD COURSES");
        btnaddcourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddcourseActionPerformed(evt);
            }
        });
        jPanel1.add(btnaddcourse, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 110, -1, -1));

        txtstudentname.setEditable(false);
        txtstudentname.setBackground(new java.awt.Color(255, 255, 255));
        txtstudentname.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jPanel1.add(txtstudentname, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 10, 160, 30));

        jSplitPane1.setTopComponent(jPanel1);

        studentcardpanel.setBackground(new java.awt.Color(204, 204, 204));
        studentcardpanel.setLayout(new java.awt.CardLayout());
        jSplitPane1.setRightComponent(studentcardpanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSplitPane1))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 750, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnmyinfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmyinfoActionPerformed
        // TODO add your handling code here:

        StudentDetailsJPanel personal=new StudentDetailsJPanel(studentcardpanel,lc);

        for (Student student : lc.SudentList)
        {
            int id =Integer.parseInt(txtstudentid.getText());
            if(id==student.getStudentUserId())
            {
                LocalDate localDate = student.getStudentDateOfBirth();
                java.util.Date utilDate = Date.from(localDate.atStartOfDay(ZoneId.systemDefault()).toInstant());

                personal.txtsid.setText(String.valueOf(id));
                personal.txtsname.setText(student.getStudentName());
                personal.txtsusername.setText(student.getStudentUsername());
                personal.txtspassword.setText(student.getStudentPassword());
                personal.jDateChooser1.setDate(utilDate);
            }

        }

        studentcardpanel.add("StudentDetailsJPanel",personal);
        CardLayout cardlayout= (CardLayout) studentcardpanel.getLayout();
        cardlayout.next(studentcardpanel);
    }//GEN-LAST:event_btnmyinfoActionPerformed

    private void txtstudentidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtstudentidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtstudentidActionPerformed

    private void btnlogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlogoutActionPerformed
        // TODO add your handling code here:
        //MainJFrame mj=new MainJFrame(lc);
        //mj.setVisible(true);
        //mj.show();
        StudentDashboard myFrame = new StudentDashboard(lc);
        int option = JOptionPane.showConfirmDialog(null, "Are you sure you want to exit?", "Confirm Exit", JOptionPane.YES_NO_OPTION);
        if (option == JOptionPane.YES_OPTION) {
                    // Close the application
                myFrame.dispose();
                MainJFrame mj=new MainJFrame(lc);
                mj.setVisible(true);
        }
    }//GEN-LAST:event_btnlogoutActionPerformed

    private void btnDeclareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeclareActionPerformed
        // TODO add your handling code here:
        TranscriptJPanel studTranscript = new TranscriptJPanel(studentcardpanel, lc, sc);
        
        int id =Integer.parseInt(txtstudentid.getText());
        studTranscript.txtstudentbyid.setText(String.valueOf(id));
        
        studentcardpanel.add("TranscriptJPanel",studTranscript);
        CardLayout cardlayout= (CardLayout) studentcardpanel.getLayout();
        cardlayout.next(studentcardpanel);
        
    }//GEN-LAST:event_btnDeclareActionPerformed

    private void btnaddcourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddcourseActionPerformed
        // TODO add your handling code here:
        StudentViewCourseJPanel studcourse=new StudentViewCourseJPanel(studentcardpanel,lc);
        
        int id =Integer.parseInt(txtstudentid.getText());
         
        studcourse.txtstudentid.setText(String.valueOf(id));
         
        studentcardpanel.add("StudentViewCourseJPanel",studcourse);
        CardLayout cardlayout= (CardLayout) studentcardpanel.getLayout();
        cardlayout.next(studentcardpanel);
    }//GEN-LAST:event_btnaddcourseActionPerformed

    private void btnmycoursesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmycoursesActionPerformed
        // TODO add your handling code here:
        
        StudentChosenCoursesJPanel checkcourse=new StudentChosenCoursesJPanel(studentcardpanel,lc);
        int id =Integer.parseInt(txtstudentid.getText());
         
        checkcourse.txtstudentmyid.setText(String.valueOf(id));
        
        studentcardpanel.add("StudentChosenCoursesJPanel",checkcourse);
        CardLayout cardlayout= (CardLayout) studentcardpanel.getLayout();
        cardlayout.next(studentcardpanel);
    }//GEN-LAST:event_btnmycoursesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                EducationSystem existingInstance = EducationSystem.getEducationInstance();
//                Student existingInstance1 = Student.getInstance();
                new StudentDashboard(existingInstance).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDeclare;
    private javax.swing.JButton btnaddcourse;
    private javax.swing.JButton btnlogout;
    private javax.swing.JButton btnmycourses;
    private javax.swing.JButton btnmyinfo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JPanel studentcardpanel;
    public javax.swing.JTextField txtstudentid;
    public javax.swing.JTextField txtstudentname;
    // End of variables declaration//GEN-END:variables
}
