/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.Student;

import java.awt.CardLayout;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.RowFilter;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import model.Main.EducationSystem;
import model.Professor.ProfessorUCourses;
import model.Professor.Professor;

/**
 *
 * @author riyasingh
 */
public class StudentViewCourseJPanel extends javax.swing.JPanel {

    /**
     * Creates new form StudentViewCourseJPanel
     */
    private JPanel studentcardpanel;
    private EducationSystem lc;
    
    public StudentViewCourseJPanel(JPanel studentcardpanel, EducationSystem lc) {
        initComponents();
        this.studentcardpanel=studentcardpanel;
        this.lc=lc;
        
        populatetable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblTable = new javax.swing.JTable();
        btncoursedetails = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        txtsearch = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtstudentid = new javax.swing.JTextField();

        setBackground(new java.awt.Color(204, 204, 255));

        tblTable.setBackground(new java.awt.Color(204, 204, 204));
        tblTable.setFont(new java.awt.Font("Sitka Text", 0, 14)); // NOI18N
        tblTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "COURSE NAME", "COURSE ID", "PROFESSOR NAME", "COURSE LANGUAGE", "COURSE REGION"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblTable);
        if (tblTable.getColumnModel().getColumnCount() > 0) {
            tblTable.getColumnModel().getColumn(0).setResizable(false);
            tblTable.getColumnModel().getColumn(1).setResizable(false);
            tblTable.getColumnModel().getColumn(2).setResizable(false);
            tblTable.getColumnModel().getColumn(3).setResizable(false);
            tblTable.getColumnModel().getColumn(4).setResizable(false);
        }

        btncoursedetails.setBackground(new java.awt.Color(0, 153, 153));
        btncoursedetails.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btncoursedetails.setForeground(new java.awt.Color(255, 255, 255));
        btncoursedetails.setText("COURSE DETAILS");
        btncoursedetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncoursedetailsActionPerformed(evt);
            }
        });

        btnBack.setBackground(new java.awt.Color(0, 153, 153));
        btnBack.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("BACK");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        txtsearch.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        txtsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsearchActionPerformed(evt);
            }
        });
        txtsearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtsearchKeyReleased(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 153, 153));
        jLabel10.setText(" SEARCH: ");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 153));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("VIEW COURSES");

        txtstudentid.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(200, 200, 200)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnBack)
                        .addGap(476, 476, 476)
                        .addComponent(btncoursedetails)
                        .addGap(200, 200, 200))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(txtstudentid, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(230, 230, 230))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 878, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(405, 405, 405)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(100, 100, 100))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(txtstudentid, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnBack)
                        .addGap(95, 95, 95))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 143, Short.MAX_VALUE)
                        .addComponent(btncoursedetails)
                        .addGap(99, 99, 99))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btncoursedetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncoursedetailsActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblTable.getSelectedRow();
        
        if (selectedRow < 0) 
        {
            JOptionPane.showMessageDialog(this, "Please select a course to view details");
            return;
        }
        
        Object cellValue = tblTable.getValueAt(selectedRow, 1);
        
        if (cellValue instanceof Integer) 
        {
            
            int courseID =(Integer)cellValue;
            
            ProfessorUCourses selectedCourse = null;
            for (ProfessorUCourses course : lc.ProfessorUCourseslist) 
            {
                if (course.getPCourseId() == courseID) 
                {
                    selectedCourse = course;
                    break;
                }
            }
            if (selectedCourse != null) {
                
                ViewCourseJPanel cview = new ViewCourseJPanel(studentcardpanel, lc);
                
                cview.txtcourseid.setText(String.valueOf(selectedCourse.getPCourseId()));
                cview.txtcourseprof.setText(selectedCourse.getCProfessorName());
                cview.txtcoursecapacity.setText(String.valueOf(selectedCourse.getCourseRegLimit()));
                cview.txtcourselang.setText(selectedCourse.getPCourseLanguage());
                cview.txtcoursename.setText(selectedCourse.getPCourseName());
                cview.txtcourseregion.setText(selectedCourse.getPCourseRegion());
                cview.datestart.setDate(Date.from(selectedCourse.getPCourseStartDate().atStartOfDay().toInstant(java.time.ZoneOffset.UTC)));
                cview.dateend.setDate(Date.from(selectedCourse.getPCourseEndDate().atStartOfDay().toInstant(java.time.ZoneOffset.UTC)));

            
                cview.txtcourseid.setEnabled(false);
                cview.txtcourseprof.setEnabled(false);
                cview.txtcoursecapacity.setEnabled(false);
                cview.txtcourselang.setEnabled(false);
                cview.txtcoursename.setEnabled(false);
                cview.txtcourseregion.setEnabled(false);
                cview.datestart.setEnabled(false);
                cview.dateend.setEnabled(false);
                
                int id =Integer.parseInt(txtstudentid.getText());
                
                cview.txtstudentmyid.setText(String.valueOf(id));
                
                studentcardpanel.add("CoursesViewJPanel", cview);
                CardLayout cardlayout = (CardLayout) studentcardpanel.getLayout();
                cardlayout.next(studentcardpanel);
            }
        } 
        else 
        {
            JOptionPane.showMessageDialog(this, "Please select a valid course ID to view details");
            return;
        }
    }//GEN-LAST:event_btncoursedetailsActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        studentcardpanel.remove(this);
        CardLayout layout = (CardLayout) studentcardpanel.getLayout();
        layout.previous(studentcardpanel);
        return;
    }//GEN-LAST:event_btnBackActionPerformed

    private void txtsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsearchActionPerformed

    private void txtsearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtsearchKeyReleased

        DefaultTableModel obj=(DefaultTableModel) tblTable.getModel();
        TableRowSorter< DefaultTableModel> obj1= new TableRowSorter<>(obj);
        tblTable.setRowSorter(obj1);
        obj1.setRowFilter(RowFilter.regexFilter(txtsearch.getText()));
    }//GEN-LAST:event_txtsearchKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btncoursedetails;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblTable;
    private javax.swing.JTextField txtsearch;
    public javax.swing.JTextField txtstudentid;
    // End of variables declaration//GEN-END:variables

    private void populatetable() {
        DefaultTableModel model=(DefaultTableModel) tblTable.getModel(); //type casting tablemodel to defaulttablemodel for jtable
        model.setRowCount(0); //deleting empty records
        
        int columnCount = model.getColumnCount();
        for (int column = 0; column < columnCount; column++) 
        {
            Class<?> columnClass = model.getColumnClass(column);
            System.out.println("Column " + column + " data type: " + columnClass.getName());
        }

        for(ProfessorUCourses pc : lc.getProfessorUCourseslist()){ //traverses through each record
            
            Object[] row=new Object[5];
            row[0]=pc; 
            row[1]=pc.getPCourseId();
            row[2]=pc.getCProfessorName();
            row[3]=pc.getPCourseLanguage();
            row[4]=pc.getPCourseRegion();
            
            model.addRow(row);
        }
    }
}
